markdown: kramdown
remote_theme: tuur29/pages-themes-cayman
darkmode: true
colors:
  gradient_left: "#000000" # Black
  gradient_right: "#333333" # Dark Gray
  header: "#FFF" # White header
  android_theme: "#FFFFFF"
  link: "#1e6bb8"
  section_title: "#FFF" # White section titles
